#配置激活的环境
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10485760 #10M
#mybatis映射文件 和别名
mybatis:
  mapper-locations: classpath:mybatis/*/*Mapper.xml
  type-aliases-package: com.by.bean
logging:
  level:
    com.by.mapper: debug

server:
  servlet:
    register-default-servlet: true #开启默认servlet 用于服务静态资源
token:
  enabled: true  #启用token
  validTime: 1000000000  #token有效时间 单位s
  pathPatterns: #配置拦截的路径
    - /api/**
  excludePathPatterns: #不拦截的路径
    - /api/sys/user/login
    - /api/upload
    - /api/sys/user/toke
    - /api/emp/**
    - /api/sys/basicinformation/toke

app:
 prefix: /api    #所有接口统一前缀
